name: macOS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile SnakeMetalDemo
        run: |
          # Compile with Xcode’s SDK on macos-latest runner
          swiftc -sdk "$(xcrun --sdk macosx --show-sdk-path)" \
            -framework Cocoa   \
            -framework Metal   \
            -framework MetalKit \
            main.swift -o SnakeMetalDemo

      - name: (Optional) Run the demo
        run: |
          # Exit zero so CI step doesn’t fail; used for smoke testing
          ./SnakeMetalDemo || true
